name: wisata_bandung
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 8.2.1 # ubahlah dengan versi terbaru
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
  # fonts:
  #   - family: Oswald
  #     fonts:
  #       - asset: lib/fonts/assets/Oswald/Oswald-Regular.ttf
        # Secara default aset yang tidak memiliki nilai weight akan memiliki bobo 400
        # - asset: lib/fonts/assets/Oswald/Oswald-Medium.ttf
        #   weight: 500
        # - asset: lib/fonts/assets/Oswald/Oswald-SemiBold.ttf
        #   weight: 600
          # style: italic -> Bisa menambahkan style
